start ssh-agent before dbus so dbus has the env vars set

diff --git a/scripts/xinitrc.in.in b/scripts/xinitrc.in.in
--- a/scripts/xinitrc.in.in
+++ b/scripts/xinitrc.in.in
@@ -100,44 +100,6 @@ cat /dev/null $XRESOURCES | xrdb -nocpp -merge -
 test -r $HOME/.Xmodmap && xmodmap $HOME/.Xmodmap
 
 
-# Use dbus-launch if installed.
-if test x"$DBUS_SESSION_BUS_ADDRESS" = x""; then
-    if type dbus-launch >/dev/null 2>&1; then
-		eval `dbus-launch --sh-syntax --exit-with-session`
-        # some older versions of dbus don't export the var properly
-        export DBUS_SESSION_BUS_ADDRESS
-    else
-        echo "Could not find dbus-launch; Xfce will not work properly" >&2
-	fi
-fi
-
-
-# launch a screensaver if enabled.  do not launch if we're root or if
-# we're in a VNC session.
-screensaver_enabled=`xfconf-query -c xfce4-session -p /startup/screensaver/enabled`
-if test $UID -gt 0 -a -z "$VNCSESSION" -a "$screensaver_enabled" != "false"; then
-    screensaver_type=`xfconf-query -c xfce4-session -p /startup/screensaver/type`
-
-    case "$screensaver_type" in
-        xscreensaver)
-            xscreensaver -no-splash &
-            ;;
-
-        gnome-screensaver)
-            gnome-screensaver &
-            ;;
-
-        *)
-            if test x"`which xscreensaver 2>/dev/null`" != x""; then
-                xscreensaver -no-splash &
-            elif test x"`which gnome-screensaver 2>/dev/null`" != x""; then
-                gnome-screensaver &
-            fi
-            ;;
-    esac
-fi
-
-
 # launch gpg-agent or ssh-agent if enabled.
 ssh_agent_enabled=`xfconf-query -c xfce4-session -p /startup/ssh-agent/enabled`
 if test "$ssh_agent_enabled" != "false"; then
@@ -188,6 +150,44 @@ if test "$ssh_agent_enabled" != "false"; then
 
         *)
             echo "Unrecognized agent type '$ssh_agent_type'" >&2
+            ;;
+    esac
+fi
+
+
+# Use dbus-launch if installed.
+if test x"$DBUS_SESSION_BUS_ADDRESS" = x""; then
+    if type dbus-launch >/dev/null 2>&1; then
+		eval `dbus-launch --sh-syntax --exit-with-session`
+        # some older versions of dbus don't export the var properly
+        export DBUS_SESSION_BUS_ADDRESS
+    else
+        echo "Could not find dbus-launch; Xfce will not work properly" >&2
+	fi
+fi
+
+
+# launch a screensaver if enabled.  do not launch if we're root or if
+# we're in a VNC session.
+screensaver_enabled=`xfconf-query -c xfce4-session -p /startup/screensaver/enabled`
+if test $UID -gt 0 -a -z "$VNCSESSION" -a "$screensaver_enabled" != "false"; then
+    screensaver_type=`xfconf-query -c xfce4-session -p /startup/screensaver/type`
+
+    case "$screensaver_type" in
+        xscreensaver)
+            xscreensaver -no-splash &
+            ;;
+
+        gnome-screensaver)
+            gnome-screensaver &
+            ;;
+
+        *)
+            if test x"`which xscreensaver 2>/dev/null`" != x""; then
+                xscreensaver -no-splash &
+            elif test x"`which gnome-screensaver 2>/dev/null`" != x""; then
+                gnome-screensaver &
+            fi
             ;;
     esac
 fi
