run xdg-user-dirs-update on startup and migrate desktop & templates dirs
(Old svn revision: 27890)

diff --git a/scripts/xinitrc.in b/scripts/xinitrc.in
--- a/scripts/xinitrc.in
+++ b/scripts/xinitrc.in
@@ -25,6 +25,40 @@ if test "x$XDG_CACHE_HOME" = "x" ; then
 fi
 [ -d "$XDG_CACHE_HOME" ] || mkdir "$XDG_CACHE_HOME"
 
+
+# set up XDG user directores.  see
+# http://freedesktop.org/wiki/Software/xdg-user-dirs
+if type xdg-user-dirs-update >/dev/null 2>&1; then
+    xdg-user-dirs-update
+fi
+
+if test -f "$XDG_CONFIG_HOME/user-dirs.dirs"; then
+    source "$XDG_CONFIG_HOME/user-dirs.dirs"
+    # i'm deliberately not 'export'-ing the XDG_ vars, because you shouldn't
+    # rely on the env vars inside apps, since the file could be changed at
+    # any time by the user.  this is solely here for migration purposes.
+
+    # a bit of user dir migration...
+    if test -d "$HOME/Desktop" -a ! -L "$HOME/Desktop" \
+            -a "$XDG_DESKTOP_DIR" \
+            -a "$HOME/Desktop" != "$XDG_DESKTOP_DIR"
+    then
+        echo "Migrating $HOME/Desktop to $XDG_DESKTOP_DIR..."
+        test -d "$XDG_DESKTOP_DIR" && rmdir "$XDG_DESKTOP_DIR"
+        mv "$HOME/Desktop" "$XDG_DESKTOP_DIR" || echo "Desktop migration failed" >&2
+    fi
+
+    if test -d "$HOME/Templates" -a ! -L "$HOME/Templates" \
+            -a "$XDG_TEMPLATES_DIR" \
+            -a "$HOME/Templates" != "$XDG_TEMPLATES_DIR"
+    then
+        echo "Migrating $HOME/Templates to $XDG_TEMPLATES_DIR..."
+        test -d "$XDG_TEMPLATES_DIR" && rmdir "$XDG_TEMPLATES_DIR"
+        mv "$HOME/Templates" "$XDG_TEMPLATES_DIR" || echo "Templates migration failed" >&2
+    fi
+fi
+
+
 # For now, start with an empty list
 XRESOURCES=""
 
